// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $game from "./routes/game.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $GameController from "./islands/GameController.tsx";
import * as $MapGuess from "./islands/MapGuess.tsx";
import * as $Moon from "./islands/Moon.tsx";
import * as $Rain from "./islands/Rain.tsx";
import * as $Stars from "./islands/Stars.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/game.tsx": $game,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/GameController.tsx": $GameController,
    "./islands/MapGuess.tsx": $MapGuess,
    "./islands/Moon.tsx": $Moon,
    "./islands/Rain.tsx": $Rain,
    "./islands/Stars.tsx": $Stars,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
